# Generated by Django 4.2.28 on 2026-03-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailstatus',
            name='folder',
            field=models.CharField(choices=[('INBOX', 'Входящие'), ('OUTBOX', 'Исходящие'), ('ARCHIVE', 'Архив'), ('TRASH', 'Корзина'), ('DRAFTS', 'Черновики')], default='INBOX', max_length=10),
        ),
    ]
